import requests

# 输入源列表文件
SOURCE_FILE = "sources.txt"
# 输出合并后的规则文件
OUTPUT_FILE = "merged_blacklist.txt"

def is_comment(line: str) -> bool:
    """判断是否为注释行/空行"""
    line = line.strip()
    if not line:
        return True
    # 覆盖 AdGuard 常见注释前缀：!、#、!!!
    if line.startswith("!") or line.startswith("#"):
        return True
    return False

def main():
    rules = set()
    with open(SOURCE_FILE, "r", encoding="utf-8") as f:
        urls = [line.strip() for line in f if line.strip() and not line.startswith("#")]

    for url in urls:
        try:
            resp = requests.get(url, timeout=30)
            resp.raise_for_status()
            count = 0
            for line in resp.text.splitlines():
                line = line.strip()
                if is_comment(line):
                    continue
                # 整行存入，完整保留规则语法
                rules.add(line)
                count += 1
            print(f"✅ 已处理: {url} ，有效规则 {count} 条")
        except Exception as e:
            print(f"❌ 下载失败 {url} : {e}")

    # 排序后写入
    sorted_rules = sorted(list(rules))
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        # 可选：在文件头加上汇总信息
        f.write("! Title: Merged DNS Blacklist\n")
        f.write(f"! Total rules: {len(sorted_rules)}\n")
        f.write("! Auto generated by GitHub Actions\n")
        f.write("\n")
        f.write("\n".join(sorted_rules))
    
    print(f"\n🎉 合并完成，共 {len(sorted_rules)} 条唯一规则")

if __name__ == "__main__":
    main()
