name: DNS黑名单合并
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '23 */8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Asia/Shanghai Timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "TZ=Asia/Shanghai" >> $GITHUB_ENV

      - name: Install requests
        run: pip install requests

      - name: Run merge script
        run: python merge.py

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add merged_blacklist.txt
          git commit -m "自动获取dns列表去重整合 $(date +'%Y-%m-%d %H:%M:%S')" || true
          git push
